# Generated by Django 3.0.1 on 2020-01-01 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pic')),
                ('desciption', models.TextField()),
                ('facebook_url', models.URLField(null=True)),
                ('linkedin_url', models.URLField(null=True)),
                ('codechef_url', models.URLField(null=True)),
                ('hackerrank_url', models.URLField(null=True)),
                ('hackerearth_url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rate_out_of_5', models.IntegerField()),
                ('per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.person')),
            ],
        ),
        migrations.CreateModel(
            name='internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=245)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('company_name', models.CharField(max_length=256)),
                ('company_url', models.URLField(max_length=256)),
                ('description', models.TextField()),
                ('per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.person')),
            ],
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=256)),
                ('startYear', models.CharField(max_length=4)),
                ('endYear', models.CharField(max_length=10)),
                ('marks', models.CharField(max_length=50)),
                ('per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.person')),
            ],
        ),
        migrations.CreateModel(
            name='certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.person')),
            ],
        ),
        migrations.CreateModel(
            name='awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('pic', models.ImageField(blank=True, upload_to='picture')),
                ('team', models.ManyToManyField(to='website.person')),
            ],
        ),
    ]
