# Generated by Django 3.0.1 on 2020-01-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200101_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='codechef_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='hackerearth_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='hackerrank_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
