# Generated by Django 3.0.1 on 2020-01-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200101_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
    ]
